#!/usr/bin/env python3
"""Render harness-engineering audit artifacts."""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List

REPORT_MARKER = ".harness_engineering_audit_report_dir"


def safe_prepare_output_dir(out_dir: Path, force: bool = False) -> None:
    out_dir = out_dir.resolve()
    if out_dir.exists():
        marker = out_dir / REPORT_MARKER
        safe_name = out_dir.name == "harness-engineering-audit"
        if not (force or marker.exists() or safe_name):
            raise SystemExit(
                f"Refusing to overwrite unmarked output directory: {out_dir}\n"
                f"Use --force only if this is intentional."
            )
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / REPORT_MARKER).write_text("generated by harness-engineering-audit\n", encoding="utf-8")


def bullet(items: List[str]) -> str:
    if not items:
        return "- None detected."
    return "\n".join(f"- {item}" for item in items)


def rec_list(recs: List[Dict[str, Any]]) -> str:
    if not recs:
        return "- None."
    lines = []
    for r in recs:
        dim = r.get("dimension", "General")
        title = r.get("title", "Recommendation")
        detail = r.get("detail", "")
        risk = r.get("risk", "unknown")
        lines.append(f"- **[{risk}] {dim}: {title}** — {detail}")
    return "\n".join(lines)


def score_table(scorecard: Dict[str, Any]) -> str:
    lines = ["| Dimension | Score | Status |", "|---|---:|---|"]
    for d in scorecard.get("dimensions", []):
        lines.append(f"| {d['name']} | {d['score']} | {d['status']} |")
    return "\n".join(lines)


def top_strengths(scorecard: Dict[str, Any]) -> List[str]:
    dims = sorted(scorecard.get("dimensions", []), key=lambda d: d.get("score", 0), reverse=True)
    return [f"{d['name']} ({d['score']}/10): {', '.join(d.get('evidence', [])[:2])}" for d in dims[:4]]


def top_weaknesses(scorecard: Dict[str, Any]) -> List[str]:
    dims = sorted(scorecard.get("dimensions", []), key=lambda d: d.get("score", 0))
    out = []
    for d in dims[:5]:
        gaps = d.get("gaps", []) or ["No specific gaps recorded; inspect dimension evidence."]
        out.append(f"{d['name']} ({d['score']}/10): {gaps[0]}")
    return out


def render_main_report(inventory: Dict[str, Any], scorecard: Dict[str, Any]) -> str:
    recs = scorecard.get("recommendations", {})
    docs = inventory.get("docs", {})
    codex = inventory.get("codex", {})
    skills = inventory.get("skills", {})
    omx = inventory.get("omx", {})
    ci = inventory.get("ci", {})
    marker_counts = inventory.get("markers", {}).get("counts", {})
    total_markers = sum(int(v) for v in marker_counts.values()) if marker_counts else 0

    return f"""# Harness Engineering Audit Report

Generated: {scorecard.get('generated_at')}
Repo: `{inventory.get('repo_root')}`

## Verdict

Overall score: **{scorecard.get('overall_score')}/10** ({scorecard.get('overall_status')})

This is an audit-first report. It does not mean the repo has been modified. Use the recommendations below as input to an approved OMX planning pass before making changes.

## Score Summary

{score_table(scorecard)}

## Strongest Areas

{bullet(top_strengths(scorecard))}

## Weakest Areas

{bullet(top_weaknesses(scorecard))}

## Evidence Snapshot

- Instruction files: {len(inventory.get('instruction_files', []))}
- Docs markdown files: {len(docs.get('files', []))}
- Docs indexes: {len(docs.get('indexes', []))}
- Authority docs: {len(docs.get('authority_docs', []))}
- Generated-artifact policy docs: {len(docs.get('generated_policy_docs', []))}
- Manifest/build files: {len(inventory.get('manifests', []))}
- CI workflows: {len(ci.get('workflows', []))}
- Repo-scoped skills: {len(skills.get('repo_skills', []))}
- MCP servers: {len(codex.get('mcp_servers', []))}
- OMX contexts: {len(omx.get('contexts', []))}
- OMX plans: {len(omx.get('plans', []))}
- Generated/report artifact candidate dirs: {len(inventory.get('generated_artifacts', {}).get('candidate_dirs', []))}
- Scaffold/legacy marker hits: {total_markers}

## Low-Risk Fix Candidates

{rec_list(recs.get('low_risk', []))}

## Medium-Risk Recommendations

{rec_list(recs.get('medium_risk', []))}

## High-Risk / Defer Recommendations

{rec_list(recs.get('high_risk', []))}

## Next OMX Step

Use `omx-handoff.md` as the input to `$deep-interview`.

```text
$deep-interview "Read .codex/reports/harness-engineering-audit/omx-handoff.md and conduct a harness-engineering review. Ask only questions that affect architecture, validation truth, instruction surfaces, or execution risk."
```
"""


def render_findings(scorecard: Dict[str, Any]) -> str:
    parts = ["# Harness Engineering Findings\n"]
    for d in scorecard.get("dimensions", []):
        parts.append(f"## {d['name']} — {d['score']}/10 ({d['status']})\n")
        parts.append("### Evidence\n")
        parts.append(bullet(d.get("evidence", [])) + "\n")
        parts.append("### Gaps\n")
        parts.append(bullet(d.get("gaps", [])) + "\n")
        parts.append("### Recommendations\n")
        parts.append(rec_list(d.get("recommendations", [])) + "\n")
    return "\n".join(parts)


def render_recommended_fixes(scorecard: Dict[str, Any]) -> str:
    recs = scorecard.get("recommendations", {})
    return f"""# Recommended Fixes

This file separates recommendations by execution risk. Implement nothing until a plan is approved.

## Low Risk / Planning Candidates

{rec_list(recs.get('low_risk', []))}

## Medium Risk / Review Required

{rec_list(recs.get('medium_risk', []))}

## High Risk / Defer Unless Explicitly Approved

{rec_list(recs.get('high_risk', []))}

## Execution Rule

Only low-risk, high-confidence items should proceed into an OMX PRD/test-spec by default. Medium and high-risk items require explicit human approval and validation design.
"""


def render_omx_handoff(inventory: Dict[str, Any], scorecard: Dict[str, Any]) -> str:
    return f"""# OMX Handoff: Harness Engineering Audit

Audit report path:

```text
.codex/reports/harness-engineering-audit/report.md
```

Inventory path:

```text
.codex/reports/harness-engineering-audit/inventory.json
```

Scorecard path:

```text
.codex/reports/harness-engineering-audit/scorecard.json
```

## Current verdict

Overall score: **{scorecard.get('overall_score')}/10** ({scorecard.get('overall_status')})

## Required read order for `$deep-interview`

1. `.codex/reports/harness-engineering-audit/report.md`
2. `.codex/reports/harness-engineering-audit/findings.md`
3. `.codex/reports/harness-engineering-audit/recommended-fixes.md`
4. `.codex/reports/harness-engineering-audit/inventory.json`
5. `.codex/reports/harness-engineering-audit/scorecard.json`
6. root `AGENTS.md` if present
7. nested `AGENTS.md` / `AGENTS.override.md` files if present
8. `.codex/config.toml` if present
9. `.agents/skills/**` metadata if present
10. `.omx/**` if present
11. docs indexes / validation docs referenced in the report

## Suggested `$deep-interview`

```text
$deep-interview "Read .codex/reports/harness-engineering-audit/omx-handoff.md and the referenced report artifacts. Conduct a strict harness-engineering review. Clarify only questions that affect instruction surfaces, validation truth, Codex/OMX/MCP/skills/hooks safety, docs authority, generated artifact lifecycle, or execution risk. Do not implement changes during the interview."
```

## Suggested `$ralplan`

```text
$ralplan "Read the harness-engineering audit report and interview output. Produce .omx/plans/prd-harness-engineering-audit.md and .omx/plans/test-spec-harness-engineering-audit.md. Planning must distinguish low-risk immediate fixes, medium-risk review items, and high-risk deferred work. The plan must include validation commands and rollback strategy."
```

## Suggested `$team`

```text
$team "Execute only approved low-risk fixes from the harness-engineering plan. Keep root AGENTS concise and map-like. Preserve repo-specific docs. Update validation evidence. Do not modify risky config, hooks, MCP, CI, or source structure without explicit approval."
```

## Suggested `$ralph`

```text
$ralph "Verify the harness-engineering cleanup. Confirm validation, report what changed, document remaining risk, and provide a stop/no-stop recommendation."
```
"""


def write_reports(inventory: Dict[str, Any], scorecard: Dict[str, Any], out_dir: Path, force: bool = False) -> None:
    safe_prepare_output_dir(out_dir, force=force)
    (out_dir / "inventory.json").write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / "scorecard.json").write_text(json.dumps(scorecard, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / "report.md").write_text(render_main_report(inventory, scorecard), encoding="utf-8")
    (out_dir / "findings.md").write_text(render_findings(scorecard), encoding="utf-8")
    (out_dir / "recommended-fixes.md").write_text(render_recommended_fixes(scorecard), encoding="utf-8")
    (out_dir / "omx-handoff.md").write_text(render_omx_handoff(inventory, scorecard), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Render harness-engineering audit reports.")
    parser.add_argument("inventory", help="Path to inventory JSON")
    parser.add_argument("scorecard", help="Path to scorecard JSON")
    parser.add_argument("--out", default=".codex/reports/harness-engineering-audit", help="Output report directory")
    parser.add_argument("--force", action="store_true", help="Allow overwrite of custom output directory")
    args = parser.parse_args()

    inventory = json.loads(Path(args.inventory).read_text(encoding="utf-8"))
    scorecard = json.loads(Path(args.scorecard).read_text(encoding="utf-8"))
    write_reports(inventory, scorecard, Path(args.out), force=args.force)
    print(f"Wrote harness-engineering audit report to {Path(args.out).resolve()}")


if __name__ == "__main__":
    main()
