#!/usr/bin/env python3
"""Write low-risk harness setup artifacts with provenance and rollback data."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable


PROVENANCE = "Generated by harness-engineering-audit"
ROLLBACK_SCHEMA = "harness-engineering-audit.setup-rollback.v1"
TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "assets" / "templates"

TARGETS = {
    "AGENTS": ("AGENTS.md", "AGENTS.md"),
    "docs-index": ("docs-index.md", "docs/README.md"),
    "validation-matrix": ("validation-matrix.md", "docs/harness/validation-matrix.md"),
    "doc-gardening": ("doc-gardening.md", "docs/harness/doc-gardening.md"),
    "task-contract": ("task-contract.md", "docs/harness/task-contract.md"),
    "agent-role-topology": ("agent-role-topology.md", "docs/harness/agent-role-topology.md"),
    "symphony-readiness": ("symphony-readiness.md", "docs/harness/symphony-readiness.md"),
    "task-state-schema": ("task-state-schema.md", "docs/harness/task-state-schema.md"),
    "observability-proof-schema": ("observability-proof-schema.md", "docs/harness/observability-proof-schema.md"),
    "recovery-reconciliation": ("recovery-reconciliation.md", "docs/harness/recovery-reconciliation.md"),
    "source-trust-policy": ("source-trust-policy.md", "docs/harness/source-trust-policy.md"),
    "evaluation-regression-harness": ("evaluation-regression-harness.md", "docs/harness/evaluation-regression-harness.md"),
    "release-merge-governance": ("release-merge-governance.md", "docs/harness/release-merge-governance.md"),
    "queue-capacity-policy": ("queue-capacity-policy.md", "docs/harness/queue-capacity-policy.md"),
    "artifact-provenance-policy": ("artifact-provenance-policy.md", "docs/harness/artifact-provenance-policy.md"),
    "cleanup-plan": ("cleanup-plan.md", "docs/harness/cleanup-plan.md"),
    "symphony-setup-handoff": ("symphony-setup-handoff.md", "docs/harness/symphony-setup-handoff.md"),
}

SYMPHONY_TEMPLATE_IDS = {
    "symphony-readiness",
    "task-contract",
    "agent-role-topology",
    "task-state-schema",
    "observability-proof-schema",
    "recovery-reconciliation",
    "queue-capacity-policy",
    "symphony-setup-handoff",
}

SAFE_SETUP_TEMPLATE_IDS = set(TARGETS) - {"symphony-setup-handoff"}

HANDOFF_TEMPLATE_BY_MODE = {
    "symphony-live-handoff": "symphony-live-handoff.md",
    "symphony-repo-local": "symphony-setup-handoff.md",
}


def read_template(template_id: str) -> str:
    filename, _ = TARGETS[template_id]
    return (TEMPLATE_DIR / filename).read_text(encoding="utf-8")


def rendered_template(template_id: str, mode: str) -> str:
    filename, _ = TARGETS[template_id]
    body = read_template(template_id).strip()
    return (
        f"<!-- {PROVENANCE} | Mode: {mode} | Source template: {filename} -->\n"
        f"{body}\n"
    )


def target_template_ids(mode: str) -> Iterable[str]:
    if mode == "symphony-repo-local":
        return sorted(SYMPHONY_TEMPLATE_IDS)
    if mode == "symphony-live-handoff":
        return []
    if mode == "safe-setup":
        return sorted(SAFE_SETUP_TEMPLATE_IDS)
    return TARGETS.keys()


def write_if_safe(repo: Path, template_id: str, mode: str, manifest: Dict[str, Any]) -> None:
    _, target_rel = TARGETS[template_id]
    target = repo / target_rel
    content = rendered_template(template_id, mode)
    if target.exists():
        existing = target.read_text(encoding="utf-8", errors="replace")
        if PROVENANCE in existing and mode == "force-ideal-harness":
            if existing != content:
                target.write_text(content, encoding="utf-8")
                manifest["modified"].append(str(target.relative_to(repo)))
            else:
                manifest["skipped"].append(str(target.relative_to(repo)))
            return
        manifest["collisions"].append(str(target.relative_to(repo)))
        manifest["skipped"].append(str(target.relative_to(repo)))
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    manifest["created"].append(str(target.relative_to(repo)))


def handoff_text(template_filename: str, mode: str) -> str:
    body = (TEMPLATE_DIR / template_filename).read_text(encoding="utf-8").strip()
    return (
        f"<!-- {PROVENANCE} | Mode: {mode} | Source template: {template_filename} -->\n"
        f"{body}\n"
    )


def write_handoff(out_dir: Path, manifest: Dict[str, Any], mode: str, filename: str) -> None:
    path = out_dir / filename
    template_filename = HANDOFF_TEMPLATE_BY_MODE[mode]
    path.write_text(handoff_text(template_filename, mode), encoding="utf-8")
    manifest["created"].append(str(path.name))


def run_setup(repo: Path, out_dir: Path, mode: str) -> Dict[str, Any]:
    manifest: Dict[str, Any] = {
        "schema": ROLLBACK_SCHEMA,
        "mode": mode,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "created": [],
        "modified": [],
        "deprecated": [],
        "collisions": [],
        "skipped": [],
    }
    if mode == "audit":
        return manifest
    out_dir.mkdir(parents=True, exist_ok=True)
    if mode == "symphony-live-handoff":
        write_handoff(out_dir, manifest, mode, "symphony-live-handoff.md")
    else:
        for template_id in target_template_ids(mode):
            write_if_safe(repo, template_id, mode, manifest)
        if mode == "symphony-repo-local":
            write_handoff(out_dir, manifest, mode, "symphony-repo-local-handoff.md")
    (out_dir / "setup-rollback-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest
